Added Clear Option for Filters used for Sorting the Tasks
CCExtractor/taskwarrior-flutter pull request #131
Opened 2023-03-03 17:40 UTC by manoj1749

closes #130 
- Added `Clear Filters` option for the filters, used for sorting the tasks in filter_drawer 
- resolving the issue #130 

### UI Images
|Before|After|
|:-------|:-------|
| ![sortBy](https://user-images.githubusercontent.com/83648898/222789737-ece5c315-b804-4580-bdb3-e77930fd4d7f.png) | ![sortBy](https://user-images.githubusercontent.com/83648898/222789782-24dbc095-bb97-44a3-8066-0f9f94ef9735.png) |

### Working Video

https://user-images.githubusercontent.com/83648898/222790020-b03dd608-e03a-4ff8-99ea-8d61b50dde55.mp4

2023-03-07 07:47 UTC, manoj1749 commented
Heyy, @NishantSinghal19 can you look into this pr

2023-03-26 02:53 UTC, virajbhartiya requested changes
It will be better to add the 'Clear Changes' Button at to bottom so it can be visually identified, adding them along with sort options will cause confusion.

2023-06-15 07:26 UTC, manoj1749 commented
Sure will update it

2023-06-15 07:34 UTC, NishantSinghal19 commented
Ok fix it then i will merge it

2023-06-15 14:36 UTC, closed without merging